import { Ticket } from "./types";

export const mockTickets: Ticket[] = [
  {
    id: "1",
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    subject: "Cannot access shared drive",
    body: "Hi IT, I'm unable to access the shared drive on the network. I keep getting an 'Access Denied' error when I try to open it. Can you help?",
    sender_email: "john.doe@company.com",
    sender_name: "John Doe",
    status: "open",
    priority: "high",
    category: "access",
  },
  {
    id: "2",
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    subject: "Printer not working",
    body: "The printer on the 3rd floor is showing an error message and won't print anything. Several people are waiting to print documents.",
    sender_email: "sarah.smith@company.com",
    sender_name: "Sarah Smith",
    status: "pending",
    priority: "medium",
    category: "hardware",
  },
  {
    id: "3",
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    subject: "Password reset request",
    body: "I forgot my password and need to reset it. Can you help me with this?",
    sender_email: "mike.johnson@company.com",
    sender_name: "Mike Johnson",
    status: "resolved",
    priority: "low",
    category: "access",
  },
  {
    id: "4",
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    subject: "VPN connection issues",
    body: "I'm working from home and can't connect to the VPN. It keeps timing out. I've tried restarting my computer but it's still not working.",
    sender_email: "lisa.williams@company.com",
    sender_name: "Lisa Williams",
    status: "open",
    priority: "urgent",
    category: "network",
  },
  {
    id: "5",
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    subject: "Software installation request",
    body: "I need Adobe Photoshop installed on my workstation for a new project. Can you please install it?",
    sender_email: "david.brown@company.com",
    sender_name: "David Brown",
    status: "pending",
    priority: "medium",
    category: "software",
  },
  {
    id: "6",
    created_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    subject: "Email not syncing",
    body: "My Outlook isn't syncing properly. I'm not receiving new emails and sent items aren't showing up.",
    sender_email: "emma.davis@company.com",
    sender_name: "Emma Davis",
    status: "resolved",
    priority: "high",
    category: "software",
  },
  {
    id: "7",
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    subject: "Computer running very slow",
    body: "My computer has been extremely slow for the past few days. It takes forever to open programs and files. Can someone take a look?",
    sender_email: "robert.miller@company.com",
    sender_name: "Robert Miller",
    status: "open",
    priority: "medium",
    category: "hardware",
  },
  {
    id: "8",
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    subject: "New employee setup",
    body: "We have a new employee starting on Monday. They'll need a computer, email account, and access to all standard systems.",
    sender_email: "hr@company.com",
    sender_name: "HR Department",
    status: "pending",
    priority: "high",
    category: "access",
  },
];
